### ISSUE TITLE
Broken link on /smt-input-language page

### ISSUE THREAD

**Issue by mtrberzi** [stp/stp.github.io#4]
On the page `stp.github.io/smt-input-language/`, in the first paragraph:

"For a longer description please read *this PDF*."

The text "this PDF" is a link to `http://stp.github.io/smt-input-language/www.grammatech.com/resource/smt/SMTLIBTutorial.pdf`. However, the link should actually be `http://www.grammatech.com/resource/smt/SMTLIBTutorial.pdf`.

**Comment by msoos** [comment]
Thanks a lot, updated!
